# Generated by Django 5.0.6 on 2024-07-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Modified', 'Modified'), ('Passive', 'Passive')], default='Active', max_length=10)),
                ('ip_address', models.GenericIPAddressField(default='10.3.25.144')),
                ('machine_name', models.CharField(default='Burak', max_length=50)),
            ],
            options={
                'db_table': 'store_category',
            },
        ),
    ]
